// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyxmlsbfjmpycttacdzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55eG1sc2Jmam1weWN0dGFjZHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjM2NjQsImV4cCI6MjA3MjgzOTY2NH0.tV0hr8yJbTz1m5Yq1oqF6dPJyrgeg3SBz-uYq95F_a8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});